namespace Tailwind.MSBuild.Tests.Common;

using System.Runtime.InteropServices;

internal static class FakeTailwindCli
{
    private const string WindowsScript = """
@echo off
setlocal EnableDelayedExpansion
set "output="
set "watch=false"

:parse
if "%~1"=="" goto afterparse
if /I "%~1"=="-o" (
  set "output=%~2"
  shift
) else if /I "%~1"=="--watch" (
  set "watch=true"
)
shift
goto parse

:afterparse
if not "%output%"=="" (
  for %%I in ("%output%") do (
    if not exist "%%~dpI" mkdir "%%~dpI" >nul 2>&1
  )
  >"%output%" echo /* generated by fake tailwind cli */
)

if /I "!watch!"=="true" (
  timeout /t 120 /nobreak >nul
)

exit /b 0
""";

    private const string UnixScript = """
#!/usr/bin/env sh
output=""
watch="false"

while [ "$#" -gt 0 ]; do
  case "$1" in
    -o)
      output="$2"
      shift 2
      ;;
    --watch)
      watch="true"
      shift
      ;;
    *)
      shift
      ;;
  esac
done

if [ -n "$output" ]; then
  mkdir -p "$(dirname "$output")"
  printf '/* generated by fake tailwind cli */\n' > "$output"
fi

if [ "$watch" = "true" ]; then
  sleep 120
fi
""";

    public static string Create(string directory, string fileNamePrefix = "tailwind-fake")
    {
        Directory.CreateDirectory(directory);

        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            var path = Path.Combine(directory, $"{fileNamePrefix}.cmd");
            File.WriteAllText(path, WindowsScript, Encoding.ASCII);
            return path;
        }

        var unixPath = Path.Combine(directory, $"{fileNamePrefix}.sh");
        File.WriteAllText(unixPath, UnixScript, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        EnsureExecutable(unixPath);
        return unixPath;
    }

    private static void EnsureExecutable(string path)
    {
        using var process = new Process
        {
            StartInfo = new ProcessStartInfo
            {
                FileName = "chmod",
                Arguments = $"+x \"{path}\"",
                UseShellExecute = false,
                RedirectStandardError = true
            }
        };

        process.Start();
        var stdErr = process.StandardError.ReadToEnd();
        process.WaitForExit();

        if (process.ExitCode != 0)
            throw new InvalidOperationException($"Unable to mark fake tailwind cli as executable: {stdErr}");
    }
}
